# Generated by Django 3.2.25 on 2026-03-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
